#!/usr/bin/env php
<?php

use App\Console\Kernel;

// Carrega o autoload do Composer
if (file_exists(__DIR__ . '/vendor/autoload.php')) {
    require __DIR__ . '/vendor/autoload.php';
} else {
    require __DIR__ . '/../../autoload.php';
}

$kernel = new Kernel();
$status = $kernel->handle();

exit($status);
